{
 "title": "Observability overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Block processing rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(thor_metrics_block_processed_count_total{success=\"true\", type=\"received\"}[3m])",
     "legendFormat": "{{server_address}}"
    }
   ]
  },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(thor_metrics_api_request_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5XX rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(thor_metrics_api_request_count_total{code=~\"5..\"}[1m]))\n/\n  sum(rate(thor_metrics_api_request_count_total[1m]))\n) * 100",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "4XX rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(thor_metrics_api_request_count_total{code=~\"4..\"}[1m]))\n/\n  sum(rate(thor_metrics_api_request_count_total[1m]))\n) * 100",
     "legendFormat": "4XX"
    }
   ]
  },
  {
   "title": "Total request count by response code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (thor_metrics_api_request_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Trace rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_received_total[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"otel_collector\"}[1m]))",
     "legendFormat": "exported"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "filters": [
      { "id": "ccb09ae4", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "edge-proxy" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node API logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"node-a|node-b\"} |= `API Request`"
    }
   ]
  }
 ]
}